version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jira:
    image: atlassian/jira-software
    container_name: jira
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jiradb
      ATL_JDBC_USER: admin
      ATL_JDBC_PASSWORD: ${JIRA_DB_PASSWORD:-adminpassword}
      ATL_DB_TYPE: postgresql
      ATL_HOME: /var/atlassian/application-data/jira
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    ports:
      - "1010:8080"
    depends_on:
      - postgres

  confluence:
    image: atlassian/confluence-server
    container_name: confluence
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confluencedb
      ATL_JDBC_USER: admin
      ATL_JDBC_PASSWORD: ${CONFLUENCE_DB_PASSWORD:-adminpassword}
      ATL_DB_TYPE: postgresql
      ATL_HOME: /var/atlassian/application-data/confluence
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    ports:
      - "2020:8090"
    depends_on:
      - postgres

volumes:
  postgres_data:
  confluence_data:
  jira_data:
